<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationTitle>ParetoTool</ApplicationTitle>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="images\paretotoollogo_large.png" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="images\paretotoollogo_large.png" />
  </ItemGroup>
</Project>
